name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  productNamespacePrefix: "ReactiveObject"

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: none
    uses: reactiveui/actions-common/.github/workflows/workflow-common-setup-and-build.yml@main
    with:
      configuration: Release
      productNamespacePrefix: "ReactiveObject"
      useVisualStudioPreview: true
      useMauiCheckDotNetTool: false
      dotNetBuild: true

